--AF/Relic/Empy set piece variables to be usable as references in other LUA files
	--WAR
	WAR_AF_HEAD = "Pummeler's Mask"
	WAR_AF_BODY = "Pummeler's Lorica"
	WAR_AF_HANDS = "Pumm. Mufflers"
	WAR_AF_LEGS = "Pumm. Cuisses"
	WAR_AF_FEET = "Pumm. Calligae"
	WAR_RELIC_HEAD = "Agoge Mask"
	WAR_RELIC_BODY = "Agoge Lorica"
	WAR_RELIC_HANDS = "Agoge Mufflers"
	WAR_RELIC_LEGS = "Agoge Cuisses"
	WAR_RELIC_FEET = "Agoge Calligae"
	WAR_EMPYREAN_HEAD = "Boii Mask"
	WAR_EMPYREAN_BODY = "Boii Lorica"
	WAR_EMPYREAN_HANDS = "Boii Mufflers"
	WAR_EMPYREAN_LEGS = "Boii Cuisses"
	WAR_EMPYREAN_FEET = "Boii Calligae"
	
	--MNK
	MNK_AF_HEAD = "Anchorite's Crown"
	MNK_AF_BODY = "Anchorite's Cyclas"
	MNK_AF_HANDS = "Anchorite's Gloves"
	MNK_AF_LEGS = "Anchorite's Hose"
	MNK_AF_FEET = "Anchorite's Gaiters"
	MNK_RELIC_HEAD = "Hesychast's Crown"
	MNK_RELIC_BODY = "Hesychast's Cyclas"
	MNK_RELIC_HANDS = "Hesychast's Gloves"
	MNK_RELIC_LEGS = "Hesychast's Hose"
	MNK_RELIC_FEET = "Hesychast's Gaiters"
	MNK_EMPYREAN_HEAD = "Bhikku Crown"
	MNK_EMPYREAN_BODY = "Bhikku Cyclas"
	MNK_EMPYREAN_HANDS = "Bhikku Gloves"
	MNK_EMPYREAN_LEGS = "Bhikku Hose"
	MNK_EMPYREAN_FEET = "Bhikku Gaiters"

	--WHM
	WHM_AF_HEAD = "Theophany Cap"
	WHM_AF_BODY = "Theophany Briault"
	WHM_AF_HANDS = "Theophany Mitts"
	WHM_AF_LEGS = "Theophany Pantaloons"
	WHM_AF_FEET = "Theophany Duckbills"
	WHM_RELIC_HEAD = "Piety Cap"
	WHM_RELIC_BODY = "Piety Briault"
	WHM_RELIC_HANDS = "Piety Mitts"
	WHM_RELIC_LEGS = "Piety Pantaloons"
	WHM_RELIC_FEET = "Piety Duckbills"
	WHM_EMPYREAN_HEAD = "Ebers Cap"
	WHM_EMPYREAN_BODY = "Ebers Briault"
	WHM_EMPYREAN_HANDS = "Ebers Mitts"
	WHM_EMPYREAN_LEGS = "Ebers Pantaloons"
	WHM_EMPYREAN_FEET = "Ebers Duckbills"

	--BLM
	BLM_AF_HEAD = "Spaekona's Petasos"
	BLM_AF_BODY = "Spaekona's Coat"
	BLM_AF_HANDS = "Spaekona's Gloves"
	BLM_AF_LEGS = "Spaekona's Chausses"
	BLM_AF_FEET = "Spaekona's Sabots"
	BLM_RELIC_HEAD = "Archmage's Petasos"
	BLM_RELIC_BODY = "Archmage's Coat"
	BLM_RELIC_HANDS = "Archmage's Gloves"
	BLM_RELIC_LEGS = "Archmage's Chausses"
	BLM_RELIC_FEET = "Archmage's Sabots"
	BLM_EMPYREAN_HEAD = "Wicce Petasos"
	BLM_EMPYREAN_BODY = "Wicce Coat"
	BLM_EMPYREAN_HANDS = "Wicce Gloves"
	BLM_EMPYREAN_LEGS = "Wicce Chausses"
	BLM_EMPYREAN_FEET = "Wicce Sabots"

	--RDM
	RDM_AF_HEAD = "Atrophy Chapeau"
	RDM_AF_BODY = "Atrophy Tabard"
	RDM_AF_HANDS = "Atrophy Gloves"
	RDM_AF_LEGS = "Atrophy Tights"
	RDM_AF_FEET = "Atrophy Boots"
	RDM_RELIC_HEAD = "Vitiation Chapeau"
	RDM_RELIC_BODY = "Vitiation Tabard"
	RDM_RELIC_HANDS = "Vitiation Gloves"
	RDM_RELIC_LEGS = "Vitiation Tights"
	RDM_RELIC_FEET = "Vitiation Boots"
	RDM_EMPYREAN_HEAD = "Lethargy Chappel"
	RDM_EMPYREAN_BODY = "Lethargy Sayon"
	RDM_EMPYREAN_HANDS = "Lethargy Gantherots"
	RDM_EMPYREAN_LEGS = "Lethargy Fuseau"
	RDM_EMPYREAN_FEET = "Lethargy Houseaux"

	--THF
	THF_AF_HEAD = "Pill. Bonnet"
	THF_AF_BODY = "Pillager's Vest"
	THF_AF_HANDS = "Pill. Armlets"
	THF_AF_LEGS = "Pill. Culottes"
	THF_AF_FEET = "Pill. Poulaines"
	THF_RELIC_HEAD = "Plunderer's Bonnet"
	THF_RELIC_BODY = "Plunderer's Vest"
	THF_RELIC_HANDS = "Plunderer's Armlets"
	THF_RELIC_LEGS = "Plunderer's Culottes"
	THF_RELIC_FEET = "Plunderer's Poulaines"
	THF_EMPYREAN_HEAD = "Skulker's Bonnet"
	THF_EMPYREAN_BODY = "Skulker's Vest"
	THF_EMPYREAN_HANDS = "Skulker's Armlets"
	THF_EMPYREAN_LEGS = "Skulker's Culottes"
	THF_EMPYREAN_FEET = "Skulker's Poulaines"

	--PLD
	PLD_AF_HEAD = "Reverence Coronet"
	PLD_AF_BODY = "Reverence Surcoat"
	PLD_AF_HANDS = "Reverence Gauntlets"
	PLD_AF_LEGS = "Reverence Breeches"
	PLD_AF_FEET = "Reverence Leggings"
	PLD_RELIC_HEAD = "Caballarius Coronet"
	PLD_RELIC_BODY = "Caballarius Surcoat"
	PLD_RELIC_HANDS = "Caballarius Gauntlets"
	PLD_RELIC_LEGS = "Caballarius Breeches"
	PLD_RELIC_FEET = "Caballarius Leggings"
	PLD_EMPYREAN_HEAD = "Chevalier's Armet"
	PLD_EMPYREAN_BODY = "Chevalier's Cuirass"
	PLD_EMPYREAN_HANDS = "Chevalier's Gauntlets"
	PLD_EMPYREAN_LEGS = "Chevalier's Cuisses"
	PLD_EMPYREAN_FEET = "Chevalier's Sabatons"

	--DRK
	DRK_AF_HEAD = "Ignominy Burgeonet"
	DRK_AF_BODY = "Ignominy Cuirass"
	DRK_AF_HANDS = "Ignominy Gauntlets"
	DRK_AF_LEGS = "Ignominy Flanchard"
	DRK_AF_FEET = "Ignominy Sollerets"
	DRK_RELIC_HEAD = "Fallen's Burgeonet"
	DRK_RELIC_BODY = "Fallen's Cuirass"
	DRK_RELIC_HANDS = "Fallen's Finger Gauntlets"
	DRK_RELIC_LEGS = "Fallen's Flanchard"
	DRK_RELIC_FEET = "Fallen's Sollerets"
	DRK_EMPYREAN_HEAD = "Heathen's Burgeonet"
	DRK_EMPYREAN_BODY = "Heathen's Cuirass"
	DRK_EMPYREAN_HANDS = "Heathen's Gauntlets"
	DRK_EMPYREAN_LEGS = "Heathen's Flanchard"
	DRK_EMPYREAN_FEET = "Heathen's Sollerets"

	--BST
	BST_AF_HEAD = "Totemic Helm"
	BST_AF_BODY = "Totemic Jackcoat"
	BST_AF_HANDS = "Totemic Gloves"
	BST_AF_LEGS = "Totemic Trousers"
	BST_AF_FEET = "Totemic Gaiters"
	BST_RELIC_HEAD = "Ankusa Helm"
	BST_RELIC_BODY = "Ankusa Jackcoat"
	BST_RELIC_HANDS = "Ankusa Gloves"
	BST_RELIC_LEGS = "Ankusa Trousers"
	BST_RELIC_FEET = "Ankusa Gaiters"
	BST_EMPYREAN_HEAD = "Nukumi Cabasset"
	BST_EMPYREAN_BODY = "Nukumi Gausape"
	BST_EMPYREAN_HANDS = "Nukumi Manoplas"
	BST_EMPYREAN_LEGS = "Nukumi Quijotes"
	BST_EMPYREAN_FEET = "Nukumi Ocreae"

	--BRD
	BRD_AF_HEAD = "Brioso Roundlet"
	BRD_AF_BODY = "Brioso Justaucorps"
	BRD_AF_HANDS = "Brioso Cuffs"
	BRD_AF_LEGS = "Brioso Cannions"
	BRD_AF_FEET = "Brioso Slippers"
	BRD_RELIC_HEAD = "Bihu Roundlet"
	BRD_RELIC_BODY = "Bihu Justaucorps"
	BRD_RELIC_HANDS = "Bihu Cuffs"
	BRD_RELIC_LEGS = "Bihu Cannions"
	BRD_RELIC_FEET = "Bihu Slippers"
	BRD_EMPYREAN_HEAD = "Fili Calot"
	BRD_EMPYREAN_BODY = "Fili Hongreline"
	BRD_EMPYREAN_HANDS = "Fili Manchettes"
	BRD_EMPYREAN_LEGS = "Fili Rhingrave"
	BRD_EMPYREAN_FEET = "Fili Cothurnes"

	--RNG
	RNG_AF_HEAD = "Orion Beret"
	RNG_AF_BODY = "Orion Jerkin"
	RNG_AF_HANDS = "Orion Bracers"
	RNG_AF_LEGS = "Orion Braccae"
	RNG_AF_FEET = "Orion Socks"
	RNG_RELIC_HEAD = "Arcadian Beret"
	RNG_RELIC_BODY = "Arcadian Jerkin"
	RNG_RELIC_HANDS = "Arcadian Bracers"
	RNG_RELIC_LEGS = "Arcadian Braccae"
	RNG_RELIC_FEET = "Arcadian Socks"
	RNG_EMPYREAN_HEAD = "Amini Gapette"
	RNG_EMPYREAN_BODY = "Amini Caban"
	RNG_EMPYREAN_HANDS = "Amini Glovelettes"
	RNG_EMPYREAN_LEGS = "Amini Brague"
	RNG_EMPYREAN_FEET = "Amini Bottillons"

	--SAM
	SAM_AF_HEAD = "Wakido Kabuto"
	SAM_AF_BODY = "Wakido Domaru"
	SAM_AF_HANDS = "Wakido Kote"
	SAM_AF_LEGS = "Wakido Haidate"
	SAM_AF_FEET = "Wakido Sune-Ate"
	SAM_RELIC_HEAD = "Sakonji Kabuto"
	SAM_RELIC_BODY = "Sakonji Domaru"
	SAM_RELIC_HANDS = "Sakonji Kote"
	SAM_RELIC_LEGS = "Sakonji Haidate"
	SAM_RELIC_FEET = "Sakonji Sune-Ate"
	SAM_EMPYREAN_HEAD = "Kasuga Kabuto"
	SAM_EMPYREAN_BODY = "Kasuga Domaru"
	SAM_EMPYREAN_HANDS = "Kasuga Kote"
	SAM_EMPYREAN_LEGS = "Kasuga Haidate"
	SAM_EMPYREAN_FEET = "Kasuga Sune-Ate"

	--NIN
	NIN_AF_HEAD = "Hachiya Hatsuburi"
	NIN_AF_BODY = "Hachiya Chainmail"
	NIN_AF_HANDS = "Hachiya Tekko"
	NIN_AF_LEGS = "Hachiya Hakama"
	NIN_AF_FEET = "Hachiya Kyahan"
	NIN_RELIC_HEAD = "Mochizuki Hatsuburi"
	NIN_RELIC_BODY = "Mochizuki Chainmail"
	NIN_RELIC_HANDS = "Mochizuki Tekko"
	NIN_RELIC_LEGS = "Mochizuki Hakama"
	NIN_RELIC_FEET = "Mochizuki Kyahan"
	NIN_EMPYREAN_HEAD = "Hattori Zukin"
	NIN_EMPYREAN_BODY = "Hattori Ningi"
	NIN_EMPYREAN_HANDS = "Hattori Tekko"
	NIN_EMPYREAN_LEGS = "Hattori Hakama"
	NIN_EMPYREAN_FEET = "Hattori Kyahan"

	--DRG
	DRG_AF_HEAD = "Vishap Armet"
	DRG_AF_BODY = "Vishap Mail"
	DRG_AF_HANDS = "Vishap Finger Gauntlets"
	DRG_AF_LEGS = "Vishap Brais"
	DRG_AF_FEET = "Vishap Greaves"
	DRG_RELIC_HEAD = "Pteroslaver Armet"
	DRG_RELIC_BODY = "Pteroslaver Mail"
	DRG_RELIC_HANDS = "Pteroslaver Finger Gauntlets"
	DRG_RELIC_LEGS = "Pteroslaver Brais"
	DRG_RELIC_FEET = "Pteroslaver Greaves"
	DRG_EMPYREAN_HEAD = "Peltast's Mezail"
	DRG_EMPYREAN_BODY = "Peltast's Plackart"
	DRG_EMPYREAN_HANDS = "Peltast's Vambraces"
	DRG_EMPYREAN_LEGS = "Peltast's Cuissots"
	DRG_EMPYREAN_FEET = "Peltast's Schynbalds"

	--SMN
	SMN_AF_HEAD = "Convoker's Horn"
	SMN_AF_BODY = "Convoker's Doublet"
	SMN_AF_HANDS = "Convoker's Bracers"
	SMN_AF_LEGS = "Convoker's Spats"
	SMN_AF_FEET = "Convoker's Pigaches"
	SMN_RELIC_HEAD = "Glyphic Horn"
	SMN_RELIC_BODY = "Glyphic Doublet"
	SMN_RELIC_HANDS = "Glyphic Bracers"
	SMN_RELIC_LEGS = "Glyphic Spats"
	SMN_RELIC_FEET = "Glyphic Pigaches"
	SMN_EMPYREAN_HEAD = "Beckoner's Horn"
	SMN_EMPYREAN_BODY = "Beckoner's Doublet"
	SMN_EMPYREAN_HANDS = "Beckoner's Bracers"
	SMN_EMPYREAN_LEGS = "Beckoner's Spats"
	SMN_EMPYREAN_FEET = "Beckoner's Pigaches"

	--BLU
	BLU_AF_HEAD = "Assimilator's Keffiyeh"
	BLU_AF_BODY = "Assimilator's Jubbah"
	BLU_AF_HANDS = "Assimilator's Bazubands"
	BLU_AF_LEGS = "Assimilator's Shalwar"
	BLU_AF_FEET = "Assimilator's Charuqs"
	BLU_RELIC_HEAD = "Luhlaza Keffiyeh"
	BLU_RELIC_BODY = "Luhlaza Jubbah"
	BLU_RELIC_HANDS = "Luhlaza Bazubands"
	BLU_RELIC_LEGS = "Luhlaza Shalwar"
	BLU_RELIC_FEET = "Luhlaza Charuqs"
	BLU_EMPYREAN_HEAD = "Hashishin Kavuk"
	BLU_EMPYREAN_BODY = "Hashishin Mintan"
	BLU_EMPYREAN_HANDS = "Hashishin Bazubands"
	BLU_EMPYREAN_LEGS = "Hashishin Tayt"
	BLU_EMPYREAN_FEET = "Hashishin Basmak"

	--COR
	COR_AF_HEAD = "Laksamana's Tricorne"
	COR_AF_BODY = "Laksamana's Frac"
	COR_AF_HANDS = "Laksamana's Gants"
	COR_AF_LEGS = "Laksamana's Trews"
	COR_AF_FEET = "Laksamana's Bottes"
	COR_RELIC_HEAD = "Lanun Tricorne"
	COR_RELIC_BODY = "Lanun Frac"
	COR_RELIC_HANDS = "Lanun Gants"
	COR_RELIC_LEGS = "Lanun Trews"
	COR_RELIC_FEET = "Lanun Bottes"
	COR_EMPYREAN_HEAD = "Chasseur's Tricorne"
	COR_EMPYREAN_BODY = "Chasseur's Frac"
	COR_EMPYREAN_HANDS = "Chasseur's Gants"
	COR_EMPYREAN_LEGS = "Chasseur's Trews"
	COR_EMPYREAN_FEET = "Chasseur's Bottes"

	--PUP
	PUP_AF_HEAD = "Foire Taj"
	PUP_AF_BODY = "Foire Tobe"
	PUP_AF_HANDS = "Foire Dastanas"
	PUP_AF_LEGS = "Foire Churidars"
	PUP_AF_FEET = "Foire Babouches"
	PUP_RELIC_HEAD = "Pitre Taj"
	PUP_RELIC_BODY = "Pitre Tobe"
	PUP_RELIC_HANDS = "Pitre Dastanas"
	PUP_RELIC_LEGS = "Pitre Churidars"
	PUP_RELIC_FEET = "Pitre Babouches"
	PUP_EMPYREAN_HEAD = "Karagoz Capello"
	PUP_EMPYREAN_BODY = "Karagoz Farsetto"
	PUP_EMPYREAN_HANDS = "Karagoz Guanti"
	PUP_EMPYREAN_LEGS = "Karagoz Pantaloni"
	PUP_EMPYREAN_FEET = "Karagoz Scarpe"

	--DNC
	DNC_AF_HEAD = "Maxixi Tiara"
	DNC_AF_BODY = "Maxixi Casaque"
	DNC_AF_HANDS = "Maxixi Bangles"
	DNC_AF_LEGS = "Maxixi Tights"
	DNC_AF_FEET = "Maxixi Toe Shoes"
	DNC_RELIC_HEAD = "Horos Tiara"
	DNC_RELIC_BODY = "Horos Casaque"
	DNC_RELIC_HANDS = "Horos Bangles"
	DNC_RELIC_LEGS = "Horos Tights"
	DNC_RELIC_FEET = "Horos Toe Shoes"
	DNC_EMPYREAN_HEAD = "Maculele Tiara"
	DNC_EMPYREAN_BODY = "Maculele Casaque"
	DNC_EMPYREAN_HANDS = "Maculele Bangles"
	DNC_EMPYREAN_LEGS = "Maculele Tights"
	DNC_EMPYREAN_FEET = "Maculele Toe Shoes"

	--SCH
	SCH_AF_HEAD = "Academic's Mortarboard"
	SCH_AF_BODY = "Academic's Gown"
	SCH_AF_HANDS = "Academic's Bracers"
	SCH_AF_LEGS = "Academic's Pants"
	SCH_AF_FEET = "Academic's Loafers"
	SCH_RELIC_HEAD = "Pedagogy Mortarboard"
	SCH_RELIC_BODY = "Pedagogy Gown"
	SCH_RELIC_HANDS = "Pedagogy Bracers"
	SCH_RELIC_LEGS = "Pedagogy Pants"
	SCH_RELIC_FEET = "Pedagogy Loafers"
	SCH_EMPYREAN_HEAD = "Arbatel Bonnet"
	SCH_EMPYREAN_BODY = "Arbatel Gown"
	SCH_EMPYREAN_HANDS = "Arbatel Bracers"
	SCH_EMPYREAN_LEGS = "Arbatel Pants"
	SCH_EMPYREAN_FEET = "Arbatel Loafers"

	--GEO
	GEO_AF_HEAD = "Geomancy Galero"
	GEO_AF_BODY = "Geomancy Tunic"
	GEO_AF_HANDS = "Geomancy Mitaines"
	GEO_AF_LEGS = "Geomancy Pants"
	GEO_AF_FEET = "Geomancy Sandals"
	GEO_RELIC_HEAD = "Bagua Galero"
	GEO_RELIC_BODY = "Bagua Tunic"
	GEO_RELIC_HANDS = "Bagua Mitaines"
	GEO_RELIC_LEGS = "Bagua Pants"
	GEO_RELIC_FEET = "Bagua Sandals"
	GEO_EMPYREAN_HEAD = "Azimuth Hood"
	GEO_EMPYREAN_BODY = "Azimuth Coat"
	GEO_EMPYREAN_HANDS = "Azimuth Gloves"
	GEO_EMPYREAN_LEGS = "Azimuth Tights"
	GEO_EMPYREAN_FEET = "Azimuth Gaiters"

	--RUN
	RUN_AF_HEAD = "Runeist Bandeau"
	RUN_AF_BODY = "Runeist Coat"
	RUN_AF_HANDS = "Runeist Mitons"
	RUN_AF_LEGS = "Runeist Trousers"
	RUN_AF_FEET = "Runeist Boots"
	RUN_RELIC_HEAD = "Futhark Bandeau"
	RUN_RELIC_BODY = "Futhark Coat"
	RUN_RELIC_HANDS = "Futhark Mitons"
	RUN_RELIC_LEGS = "Futhark Trousers"
	RUN_RELIC_FEET = "Futhark Boots"
	RUN_EMPYREAN_HEAD = "Erilaz Galea"
	RUN_EMPYREAN_BODY = "Erilaz Surcoat"
	RUN_EMPYREAN_HANDS = "Erilaz Gauntlets"
	RUN_EMPYREAN_LEGS = "Erilaz Leg Guards"
	RUN_EMPYREAN_FEET = "Erilaz Greaves"