--AF/Relic/Empy set piece variables to be usable as references in other LUA files
--['WAR']
REMA = {
	['WAR']={
        ['AF']={
            ['HEAD'] = {Head = "Pummeler's Mask"},
	        ['BODY'] = {Body="Pummeler's Lorica"},
	        ['HANDS'] = {Hands="Pumm. Mufflers"},
	        ['LEGS'] = {Legs="Pumm. Cuisses"},
	        ['FEET'] = {Feet="Pumm. Calligae"},
        },
	    ['RELIC']={
            ['HEAD'] ={Head = "Agoge Mask"}, 
            ['BODY'] ={Body = "Agoge Lorica"}, 
            ['HANDS'] ={Hands = "Agoge Mufflers"}, 
            ['LEGS'] ={Legs = "Agoge Cuisses"}, 
            ['FEET'] ={Feet = "Agoge Calligae}",
    },
        ['EMPYREAN']={
            ['HEAD'] = {"Boii Mask"},
            ['BODY'] = {"Boii Lorica"},
            ['HANDS'] = {"Boii Mufflers"},
            ['LEGS'] = {"Boii Cuisses"},
            ['FEET'] = {"Boii Calligae"},
        }
    }
},

-- --['MNK']
-- 	['MNK']['AF']['HEAD'] = "Anchorite's Crown", 
--     ['MNK']['AF']['BODY'] = "Anchorite's Cyclas", 
--     ['MNK']['AF']['HANDS'] = "Anchorite's Gloves", 
--     ['MNK']['AF']['LEGS'] = "Anchorite's Hose", 
--     ['MNK']['AF']['FEET'] = "Anchorite's Gaiters", 
--     ['MNK']['RELIC']['HEAD'] = "Hesychast's Crown", 
--     ['MNK']['RELIC']['BODY'] = "Hesychast's Cyclas", 
--     ['MNK']['RELIC']['HANDS'] = "Hesychast's Gloves", 
--     ['MNK']['RELIC']['LEGS'] = "Hesychast's Hose", 
--     ['MNK']['RELIC']['FEET'] = "Hesychast's Gaiters", 
--     ['MNK']['EMPYREAN']['HEAD'] = "Bhikku Crown", 
--     ['MNK']['EMPYREAN']['BODY'] = "Bhikku Cyclas", 
--     ['MNK']['EMPYREAN']['HANDS'] = "Bhikku Gloves", 
--     ['MNK']['EMPYREAN']['LEGS'] = "Bhikku Hose", 
--     ['MNK']['EMPYREAN']['FEET'] = "Bhikku Gaiters", 
--     --['WHM']
-- 	['WHM']['AF']['HEAD'] = "Theophany Cap", 
--     ['WHM']['AF']['BODY'] = "Theophany Briault", 
--     ['WHM']['AF']['HANDS'] = "Theophany Mitts", 
--     ['WHM']['AF']['LEGS'] = "Theophany Pantaloons", 
--     ['WHM']['AF']['FEET'] = "Theophany Duckbills", 
--     ['WHM']['RELIC']['HEAD'] = "Piety Cap", 
--     ['WHM']['RELIC']['BODY'] = "Piety Briault", 
--     ['WHM']['RELIC']['HANDS'] = "Piety Mitts", 
--     ['WHM']['RELIC']['LEGS'] = "Piety Pantaloons", 
--     ['WHM']['RELIC']['FEET'] = "Piety Duckbills", 
--     ['WHM']['EMPYREAN']['HEAD'] = "Ebers Cap", 
--     ['WHM']['EMPYREAN']['BODY'] = "Ebers Briault", 
--     ['WHM']['EMPYREAN']['HANDS'] = "Ebers Mitts", 
--     ['WHM']['EMPYREAN']['LEGS'] = "Ebers Pantaloons", 
--     ['WHM']['EMPYREAN']['FEET'] = "Ebers Duckbills", 
--     --['BLM']
-- 	['BLM']['AF']['HEAD'] = "Spaekona's Petasos", 
--     ['BLM']['AF']['BODY'] = "Spaekona's Coat", 
--     ['BLM']['AF']['HANDS'] = "Spaekona's Gloves", 
--     ['BLM']['AF']['LEGS'] = "Spaekona's Chausses", 
--     ['BLM']['AF']['FEET'] = "Spaekona's Sabots", 
--     ['BLM']['RELIC']['HEAD'] = "Archmage's Petasos", 
--     ['BLM']['RELIC']['BODY'] = "Archmage's Coat", 
--     ['BLM']['RELIC']['HANDS'] = "Archmage's Gloves", 
--     ['BLM']['RELIC']['LEGS'] = "Archmage's Chausses", 
--     ['BLM']['RELIC']['FEET'] = "Archmage's Sabots", 
--     ['BLM']['EMPYREAN']['HEAD'] = "Wicce Petasos", 
--     ['BLM']['EMPYREAN']['BODY'] = "Wicce Coat", 
--     ['BLM']['EMPYREAN']['HANDS'] = "Wicce Gloves", 
--     ['BLM']['EMPYREAN']['LEGS'] = "Wicce Chausses", 
--     ['BLM']['EMPYREAN']['FEET'] = "Wicce Sabots", 
--     --['RDM']
-- 	['RDM']['AF']['HEAD'] = "Atrophy Chapeau", 
--     ['RDM']['AF']['BODY'] = "Atrophy Tabard", 
--     ['RDM']['AF']['HANDS'] = "Atrophy Gloves", 
--     ['RDM']['AF']['LEGS'] = "Atrophy Tights", 
--     ['RDM']['AF']['FEET'] = "Atrophy Boots", 
--     ['RDM']['RELIC']['HEAD'] = "Vitiation Chapeau", 
--     ['RDM']['RELIC']['BODY'] = "Vitiation Tabard", 
--     ['RDM']['RELIC']['HANDS'] = "Vitiation Gloves", 
--     ['RDM']['RELIC']['LEGS'] = "Vitiation Tights", 
--     ['RDM']['RELIC']['FEET'] = "Vitiation Boots", 
--     ['RDM']['EMPYREAN']['HEAD'] = "Lethargy Chappel", 
--     ['RDM']['EMPYREAN']['BODY'] = "Lethargy Sayon", 
--     ['RDM']['EMPYREAN']['HANDS'] = "Lethargy Gantherots", 
--     ['RDM']['EMPYREAN']['LEGS'] = "Lethargy Fuseau", 
--     ['RDM']['EMPYREAN']['FEET'] = "Lethargy Houseaux", 
    --['THF']
	THF = {
        AF = {
            HEAD = "Pill. Bonnet",
            BODY = "Pillager's Vest",
            HANDS = "Pill. Armlets",
            LEGS = "Pill. Culottes",
            FEET = "Pill. Poulaines"
        },
        RELIC = {
            HEAD = "Plunderer's Bonnet",
            BODY = "Plunderer's Vest",
            HANDS = "Plunderer's Armlets",
            LEGS = "Plunderer's Culottes",
            FEET = "Plunderer's Poulaines"
        },
        EMPYREAN = {
            HEAD = "Skulker's Bonnet",
            BODY = "Skulker's Vest",
            HANDS = "Skulker's Armlets",
            LEGS = "Skulker's Culottes",
            FEET = "Skulker's Poulaines"
        }
--     }
--     --['PLD']
-- 	['PLD']['AF']['HEAD'] = "Reverence ['COR']onet", 
--     ['PLD']['AF']['BODY'] = "Reverence Surcoat", 
--     ['PLD']['AF']['HANDS'] = "Reverence Gauntlets", 
--     ['PLD']['AF']['LEGS'] = "Reverence Breeches", 
--     ['PLD']['AF']['FEET'] = "Reverence Leggings", 
--     ['PLD']['RELIC']['HEAD'] = "Caballarius ['COR']onet", 
--     ['PLD']['RELIC']['BODY'] = "Caballarius Surcoat", 
--     ['PLD']['RELIC']['HANDS'] = "Caballarius Gauntlets", 
--     ['PLD']['RELIC']['LEGS'] = "Caballarius Breeches", 
--     ['PLD']['RELIC']['FEET'] = "Caballarius Leggings", 
--     ['PLD']['EMPYREAN']['HEAD'] = "Chevalier's Armet", 
--     ['PLD']['EMPYREAN']['BODY'] = "Chevalier's Cuirass", 
--     ['PLD']['EMPYREAN']['HANDS'] = "Chevalier's Gauntlets", 
--     ['PLD']['EMPYREAN']['LEGS'] = "Chevalier's Cuisses", 
--     ['PLD']['EMPYREAN']['FEET'] = "Chevalier's Sabatons", 
--     --['DRK']
-- 	['DRK']['AF']['HEAD'] = "Ignominy Bur['GEO']net", 
--     ['DRK']['AF']['BODY'] = "Ignominy Cuirass", 
--     ['DRK']['AF']['HANDS'] = "Ignominy Gauntlets", 
--     ['DRK']['AF']['LEGS'] = "Ignominy Flanchard", 
--     ['DRK']['AF']['FEET'] = "Ignominy Sollerets", 
--     ['DRK']['RELIC']['HEAD'] = "Fallen's Bur['GEO']net", 
--     ['DRK']['RELIC']['BODY'] = "Fallen's Cuirass", 
--     ['DRK']['RELIC']['HANDS'] = "Fallen's Finger Gauntlets", 
--     ['DRK']['RELIC']['LEGS'] = "Fallen's Flanchard", 
--     ['DRK']['RELIC']['FEET'] = "Fallen's Sollerets", 
--     ['DRK']['EMPYREAN']['HEAD'] = "Heathen's Bur['GEO']net", 
--     ['DRK']['EMPYREAN']['BODY'] = "Heathen's Cuirass", 
--     ['DRK']['EMPYREAN']['HANDS'] = "Heathen's Gauntlets", 
--     ['DRK']['EMPYREAN']['LEGS'] = "Heathen's Flanchard", 
--     ['DRK']['EMPYREAN']['FEET'] = "Heathen's Sollerets", 
--     --['BST']
-- 	['BST']['AF']['HEAD'] = "Totemic Helm", 
--     ['BST']['AF']['BODY'] = "Totemic Jackcoat", 
--     ['BST']['AF']['HANDS'] = "Totemic Gloves", 
--     ['BST']['AF']['LEGS'] = "Totemic Trousers", 
--     ['BST']['AF']['FEET'] = "Totemic Gaiters", 
--     ['BST']['RELIC']['HEAD'] = "Ankusa Helm", 
--     ['BST']['RELIC']['BODY'] = "Ankusa Jackcoat", 
--     ['BST']['RELIC']['HANDS'] = "Ankusa Gloves", 
--     ['BST']['RELIC']['LEGS'] = "Ankusa Trousers", 
--     ['BST']['RELIC']['FEET'] = "Ankusa Gaiters", 
--     ['BST']['EMPYREAN']['HEAD'] = "Nukumi Cabasset", 
--     ['BST']['EMPYREAN']['BODY'] = "Nukumi Gausape", 
--     ['BST']['EMPYREAN']['HANDS'] = "Nukumi Manoplas", 
--     ['BST']['EMPYREAN']['LEGS'] = "Nukumi Quijotes", 
--     ['BST']['EMPYREAN']['FEET'] = "Nukumi Ocreae", 
--     --['BRD']
-- 	['BRD']['AF']['HEAD'] = "Brioso Roundlet", 
--     ['BRD']['AF']['BODY'] = "Brioso Justau['COR']ps", 
--     ['BRD']['AF']['HANDS'] = "Brioso Cuffs", 
--     ['BRD']['AF']['LEGS'] = "Brioso Cannions", 
--     ['BRD']['AF']['FEET'] = "Brioso Slippers", 
--     ['BRD']['RELIC']['HEAD'] = "Bihu Roundlet", 
--     ['BRD']['RELIC']['BODY'] = "Bihu Justau['COR']ps", 
--     ['BRD']['RELIC']['HANDS'] = "Bihu Cuffs", 
--     ['BRD']['RELIC']['LEGS'] = "Bihu Cannions", 
--     ['BRD']['RELIC']['FEET'] = "Bihu Slippers", 
--     ['BRD']['EMPYREAN']['HEAD'] = "Fili Calot", 
--     ['BRD']['EMPYREAN']['BODY'] = "Fili Hongreline", 
--     ['BRD']['EMPYREAN']['HANDS'] = "Fili Manchettes", 
--     ['BRD']['EMPYREAN']['LEGS'] = "Fili Rhingrave", 
--     ['BRD']['EMPYREAN']['FEET'] = "Fili Cothurnes", 
--     --['RNG']
-- 	['RNG']['AF']['HEAD'] = "Orion Beret", 
--     ['RNG']['AF']['BODY'] = "Orion Jerkin", 
--     ['RNG']['AF']['HANDS'] = "Orion Bracers", 
--     ['RNG']['AF']['LEGS'] = "Orion Braccae", 
--     ['RNG']['AF']['FEET'] = "Orion Socks", 
--     ['RNG']['RELIC']['HEAD'] = "Arcadian Beret", 
--     ['RNG']['RELIC']['BODY'] = "Arcadian Jerkin", 
--     ['RNG']['RELIC']['HANDS'] = "Arcadian Bracers", 
--     ['RNG']['RELIC']['LEGS'] = "Arcadian Braccae", 
--     ['RNG']['RELIC']['FEET'] = "Arcadian Socks", 
--     ['RNG']['EMPYREAN']['HEAD'] = "Amini Gapette", 
--     ['RNG']['EMPYREAN']['BODY'] = "Amini Caban", 
--     ['RNG']['EMPYREAN']['HANDS'] = "Amini Glovelettes", 
--     ['RNG']['EMPYREAN']['LEGS'] = "Amini Brague", 
--     ['RNG']['EMPYREAN']['FEET'] = "Amini Bottillons", 
--     --['SAM']
-- 	['SAM']['AF']['HEAD'] = "Wakido Kabuto", 
--     ['SAM']['AF']['BODY'] = "Wakido Domaru", 
--     ['SAM']['AF']['HANDS'] = "Wakido Kote", 
--     ['SAM']['AF']['LEGS'] = "Wakido Haidate", 
--     ['SAM']['AF']['FEET'] = "Wakido Sune-Ate", 
--     ['SAM']['RELIC']['HEAD'] = "Sakonji Kabuto", 
--     ['SAM']['RELIC']['BODY'] = "Sakonji Domaru", 
--     ['SAM']['RELIC']['HANDS'] = "Sakonji Kote", 
--     ['SAM']['RELIC']['LEGS'] = "Sakonji Haidate", 
--     ['SAM']['RELIC']['FEET'] = "Sakonji Sune-Ate", 
--     ['SAM']['EMPYREAN']['HEAD'] = "Kasuga Kabuto", 
--     ['SAM']['EMPYREAN']['BODY'] = "Kasuga Domaru", 
--     ['SAM']['EMPYREAN']['HANDS'] = "Kasuga Kote", 
--     ['SAM']['EMPYREAN']['LEGS'] = "Kasuga Haidate", 
--     ['SAM']['EMPYREAN']['FEET'] = "Kasuga Sune-Ate", 
--     --['NIN']
-- 	['NIN']['AF']['HEAD'] = "Hachiya Hatsuburi", 
--     ['NIN']['AF']['BODY'] = "Hachiya Chainmail", 
--     ['NIN']['AF']['HANDS'] = "Hachiya Tekko", 
--     ['NIN']['AF']['LEGS'] = "Hachiya Hakama", 
--     ['NIN']['AF']['FEET'] = "Hachiya Kyahan", 
--     ['NIN']['RELIC']['HEAD'] = "Mochizuki Hatsuburi", 
--     ['NIN']['RELIC']['BODY'] = "Mochizuki Chainmail", 
--     ['NIN']['RELIC']['HANDS'] = "Mochizuki Tekko", 
--     ['NIN']['RELIC']['LEGS'] = "Mochizuki Hakama", 
--     ['NIN']['RELIC']['FEET'] = "Mochizuki Kyahan", 
--     ['NIN']['EMPYREAN']['HEAD'] = "Hattori Zukin", 
--     ['NIN']['EMPYREAN']['BODY'] = "Hattori ['NIN']gi", 
--     ['NIN']['EMPYREAN']['HANDS'] = "Hattori Tekko", 
--     ['NIN']['EMPYREAN']['LEGS'] = "Hattori Hakama", 
--     ['NIN']['EMPYREAN']['FEET'] = "Hattori Kyahan", 
--     --['DRG']
-- 	['DRG']['AF']['HEAD'] = "Vishap Armet", 
--     ['DRG']['AF']['BODY'] = "Vishap Mail", 
--     ['DRG']['AF']['HANDS'] = "Vishap Finger Gauntlets", 
--     ['DRG']['AF']['LEGS'] = "Vishap Brais", 
--     ['DRG']['AF']['FEET'] = "Vishap Greaves", 
--     ['DRG']['RELIC']['HEAD'] = "Pteroslaver Armet", 
--     ['DRG']['RELIC']['BODY'] = "Pteroslaver Mail", 
--     ['DRG']['RELIC']['HANDS'] = "Pteroslaver Finger Gauntlets", 
--     ['DRG']['RELIC']['LEGS'] = "Pteroslaver Brais", 
--     ['DRG']['RELIC']['FEET'] = "Pteroslaver Greaves", 
--     ['DRG']['EMPYREAN']['HEAD'] = "Peltast's Mezail", 
--     ['DRG']['EMPYREAN']['BODY'] = "Peltast's Plackart", 
--     ['DRG']['EMPYREAN']['HANDS'] = "Peltast's Vambraces", 
--     ['DRG']['EMPYREAN']['LEGS'] = "Peltast's Cuissots", 
--     ['DRG']['EMPYREAN']['FEET'] = "Peltast's ['SCH']ynbalds", 
--     --['SMN']
-- 	['SMN']['AF']['HEAD'] = "Convoker's Horn", 
--     ['SMN']['AF']['BODY'] = "Convoker's Doublet", 
--     ['SMN']['AF']['HANDS'] = "Convoker's Bracers", 
--     ['SMN']['AF']['LEGS'] = "Convoker's Spats", 
--     ['SMN']['AF']['FEET'] = "Convoker's Pigaches", 
--     ['SMN']['RELIC']['HEAD'] = "Glyphic Horn", 
--     ['SMN']['RELIC']['BODY'] = "Glyphic Doublet", 
--     ['SMN']['RELIC']['HANDS'] = "Glyphic Bracers", 
--     ['SMN']['RELIC']['LEGS'] = "Glyphic Spats", 
--     ['SMN']['RELIC']['FEET'] = "Glyphic Pigaches", 
--     ['SMN']['EMPYREAN']['HEAD'] = "Beckoner's Horn", 
--     ['SMN']['EMPYREAN']['BODY'] = "Beckoner's Doublet", 
--     ['SMN']['EMPYREAN']['HANDS'] = "Beckoner's Bracers", 
--     ['SMN']['EMPYREAN']['LEGS'] = "Beckoner's Spats", 
--     ['SMN']['EMPYREAN']['FEET'] = "Beckoner's Pigaches", 
--     --['BLU']
-- 	['BLU']['AF']['HEAD'] = "Assimilator's Keffiyeh", 
--     ['BLU']['AF']['BODY'] = "Assimilator's Jubbah", 
--     ['BLU']['AF']['HANDS'] = "Assimilator's Bazubands", 
--     ['BLU']['AF']['LEGS'] = "Assimilator's Shal['WAR']", 
--     ['BLU']['AF']['FEET'] = "Assimilator's Charuqs", 
--     ['BLU']['RELIC']['HEAD'] = "Luhlaza Keffiyeh", 
--     ['BLU']['RELIC']['BODY'] = "Luhlaza Jubbah", 
--     ['BLU']['RELIC']['HANDS'] = "Luhlaza Bazubands", 
--     ['BLU']['RELIC']['LEGS'] = "Luhlaza Shal['WAR']", 
--     ['BLU']['RELIC']['FEET'] = "Luhlaza Charuqs", 
--     ['BLU']['EMPYREAN']['HEAD'] = "Hashishin Kavuk", 
--     ['BLU']['EMPYREAN']['BODY'] = "Hashishin Mintan", 
--     ['BLU']['EMPYREAN']['HANDS'] = "Hashishin Bazubands", 
--     ['BLU']['EMPYREAN']['LEGS'] = "Hashishin Tayt", 
--     ['BLU']['EMPYREAN']['FEET'] = "Hashishin Basmak", 
--     --['COR']
-- 	['COR']['AF']['HEAD'] = "Lak['SAM']ana's Tri['COR']ne", 
--     ['COR']['AF']['BODY'] = "Lak['SAM']ana's Frac", 
--     ['COR']['AF']['HANDS'] = "Lak['SAM']ana's Gants", 
--     ['COR']['AF']['LEGS'] = "Lak['SAM']ana's Trews", 
--     ['COR']['AF']['FEET'] = "Lak['SAM']ana's Bottes", 
--     ['COR']['RELIC']['HEAD'] = "Lanun Tri['COR']ne", 
--     ['COR']['RELIC']['BODY'] = "Lanun Frac", 
--     ['COR']['RELIC']['HANDS'] = "Lanun Gants", 
--     ['COR']['RELIC']['LEGS'] = "Lanun Trews", 
--     ['COR']['RELIC']['FEET'] = "Lanun Bottes", 
--     ['COR']['EMPYREAN']['HEAD'] = "Chasseur's Tri['COR']ne", 
--     ['COR']['EMPYREAN']['BODY'] = "Chasseur's Frac", 
--     ['COR']['EMPYREAN']['HANDS'] = "Chasseur's Gants", 
--     ['COR']['EMPYREAN']['LEGS'] = "Chasseur's Trews", 
--     ['COR']['EMPYREAN']['FEET'] = "Chasseur's Bottes", 
--     --['PUP']
-- 	['PUP']['AF']['HEAD'] = "Foire Taj", 
--     ['PUP']['AF']['BODY'] = "Foire Tobe", 
--     ['PUP']['AF']['HANDS'] = "Foire Dastanas", 
--     ['PUP']['AF']['LEGS'] = "Foire Churidars", 
--     ['PUP']['AF']['FEET'] = "Foire Babouches", 
--     ['PUP']['RELIC']['HEAD'] = "Pitre Taj", 
--     ['PUP']['RELIC']['BODY'] = "Pitre Tobe", 
--     ['PUP']['RELIC']['HANDS'] = "Pitre Dastanas", 
--     ['PUP']['RELIC']['LEGS'] = "Pitre Churidars", 
--     ['PUP']['RELIC']['FEET'] = "Pitre Babouches", 
--     ['PUP']['EMPYREAN']['HEAD'] = "Karagoz Capello", 
--     ['PUP']['EMPYREAN']['BODY'] = "Karagoz Farsetto", 
--     ['PUP']['EMPYREAN']['HANDS'] = "Karagoz Guanti", 
--     ['PUP']['EMPYREAN']['LEGS'] = "Karagoz Pantaloni", 
--     ['PUP']['EMPYREAN']['FEET'] = "Karagoz Scarpe", 
--     --['DNC']
-- 	['DNC']['AF']['HEAD'] = "Maxixi Tiara", 
--     ['DNC']['AF']['BODY'] = "Maxixi Casaque", 
--     ['DNC']['AF']['HANDS'] = "Maxixi Bangles", 
--     ['DNC']['AF']['LEGS'] = "Maxixi Tights", 
--     ['DNC']['AF']['FEET'] = "Maxixi Toe Shoes", 
--     ['DNC']['RELIC']['HEAD'] = "Horos Tiara", 
--     ['DNC']['RELIC']['BODY'] = "Horos Casaque", 
--     ['DNC']['RELIC']['HANDS'] = "Horos Bangles", 
--     ['DNC']['RELIC']['LEGS'] = "Horos Tights", 
--     ['DNC']['RELIC']['FEET'] = "Horos Toe Shoes", 
--     ['DNC']['EMPYREAN']['HEAD'] = "Maculele Tiara", 
--     ['DNC']['EMPYREAN']['BODY'] = "Maculele Casaque", 
--     ['DNC']['EMPYREAN']['HANDS'] = "Maculele Bangles", 
--     ['DNC']['EMPYREAN']['LEGS'] = "Maculele Tights", 
--     ['DNC']['EMPYREAN']['FEET'] = "Maculele Toe Shoes", 
--     --['SCH']
-- 	['SCH']['AF']['HEAD'] = "Academic's Mortarboard", 
--     ['SCH']['AF']['BODY'] = "Academic's Gown", 
--     ['SCH']['AF']['HANDS'] = "Academic's Bracers", 
--     ['SCH']['AF']['LEGS'] = "Academic's Pants", 
--     ['SCH']['AF']['FEET'] = "Academic's Loafers", 
--     ['SCH']['RELIC']['HEAD'] = "Pedagogy Mortarboard", 
--     ['SCH']['RELIC']['BODY'] = "Pedagogy Gown", 
--     ['SCH']['RELIC']['HANDS'] = "Pedagogy Bracers", 
--     ['SCH']['RELIC']['LEGS'] = "Pedagogy Pants", 
--     ['SCH']['RELIC']['FEET'] = "Pedagogy Loafers", 
--     ['SCH']['EMPYREAN']['HEAD'] = "Arbatel Bonnet", 
--     ['SCH']['EMPYREAN']['BODY'] = "Arbatel Gown", 
--     ['SCH']['EMPYREAN']['HANDS'] = "Arbatel Bracers", 
--     ['SCH']['EMPYREAN']['LEGS'] = "Arbatel Pants", 
--     ['SCH']['EMPYREAN']['FEET'] = "Arbatel Loafers", 
--     --['GEO']
-- 	['GEO']['AF']['HEAD'] = "['GEO']mancy Galero", 
--     ['GEO']['AF']['BODY'] = "['GEO']mancy Tunic", 
--     ['GEO']['AF']['HANDS'] = "['GEO']mancy Mitaines", 
--     ['GEO']['AF']['LEGS'] = "['GEO']mancy Pants", 
--     ['GEO']['AF']['FEET'] = "['GEO']mancy Sandals", 
--     ['GEO']['RELIC']['HEAD'] = "Bagua Galero", 
--     ['GEO']['RELIC']['BODY'] = "Bagua Tunic", 
--     ['GEO']['RELIC']['HANDS'] = "Bagua Mitaines", 
--     ['GEO']['RELIC']['LEGS'] = "Bagua Pants", 
--     ['GEO']['RELIC']['FEET'] = "Bagua Sandals", 
--     ['GEO']['EMPYREAN']['HEAD'] = "Azimuth Hood", 
--     ['GEO']['EMPYREAN']['BODY'] = "Azimuth Coat", 
--     ['GEO']['EMPYREAN']['HANDS'] = "Azimuth Gloves", 
--     ['GEO']['EMPYREAN']['LEGS'] = "Azimuth Tights", 
--     ['GEO']['EMPYREAN']['FEET'] = "Azimuth Gaiters", 
--     --['RUN']
-- 	['RUN']['AF']['HEAD'] = "['RUN']eist Bandeau", 
--     ['RUN']['AF']['BODY'] = "['RUN']eist Coat", 
--     ['RUN']['AF']['HANDS'] = "['RUN']eist Mitons", 
--     ['RUN']['AF']['LEGS'] = "['RUN']eist Trousers", 
--     ['RUN']['AF']['FEET'] = "['RUN']eist Boots", 
--     ['RUN']['RELIC']['HEAD'] = "Futhark Bandeau", 
--     ['RUN']['RELIC']['BODY'] = "Futhark Coat", 
--     ['RUN']['RELIC']['HANDS'] = "Futhark Mitons", 
--     ['RUN']['RELIC']['LEGS'] = "Futhark Trousers", 
--     ['RUN']['RELIC']['FEET'] = "Futhark Boots", 
--     ['RUN']['EMPYREAN']['HEAD'] = "Erilaz Galea", 
--     ['RUN']['EMPYREAN']['BODY'] = "Erilaz Surcoat", 
--     ['RUN']['EMPYREAN']['HANDS'] = "Erilaz Gauntlets", 
--     ['RUN']['EMPYREAN']['LEGS'] = "Erilaz Leg Guards", 
--     ['RUN']['EMPYREAN']['FEET'] = "Erilaz Greaves"
}}